---
  # :logfile: log/workers.log
  development:
    :verbose: true
    :concurrency: 2
    :queues:
    - ['analysis_slave', 4]
    - ['field_agent_notifier', 3] 
    - ['default', 2]
    - ['low', 1]